import { defineConfig } from "tsup";
import typesugar from "unplugin-typesugar/esbuild";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "typeclasses/index": "src/typeclasses/index.ts",
    "typeclasses/flatmap": "src/typeclasses/flatmap.ts",
    "extensions/index": "src/extensions/index.ts",
    "data/index": "src/data/index.ts",
    "macros/index": "src/macros/index.ts",
    // PEP-052 syntax-activation markers
    "syntax/eq": "src/syntax/eq.ts",
    "syntax/eq/ops": "src/syntax/eq/ops.ts",
    "syntax/ord": "src/syntax/ord.ts",
    "syntax/ord/ops": "src/syntax/ord/ops.ts",
    "syntax/semigroup": "src/syntax/semigroup.ts",
    "syntax/semigroup/ops": "src/syntax/semigroup/ops.ts",
    "syntax/monoid": "src/syntax/monoid.ts",
    "syntax/monoid/ops": "src/syntax/monoid/ops.ts",
    "syntax/group": "src/syntax/group.ts",
    "syntax/group/ops": "src/syntax/group/ops.ts",
    "syntax/numeric": "src/syntax/numeric.ts",
    "syntax/numeric/ops": "src/syntax/numeric/ops.ts",
    "syntax/integral": "src/syntax/integral.ts",
    "syntax/integral/ops": "src/syntax/integral/ops.ts",
    "syntax/fractional": "src/syntax/fractional.ts",
    "syntax/fractional/ops": "src/syntax/fractional/ops.ts",
    "syntax/clone": "src/syntax/clone.ts",
    "syntax/debug": "src/syntax/debug.ts",
    "syntax/default": "src/syntax/default.ts",
    "syntax/json": "src/syntax/json.ts",
    "syntax/type-guard": "src/syntax/type-guard.ts",
  },
  format: ["cjs", "esm"],
  dts: !process.env.TYPESUGAR_SKIP_DTS,
  sourcemap: true,
  clean: true,
  external: ["typescript", "@typesugar/core", "@typesugar/macros"],
  esbuildPlugins: [typesugar()],
});
