/**
 * Built-in diagnostic suppression rules
 *
 * Rule 4 (MacroGenerated): Suppresses diagnostics in macro-generated code
 * whose source positions cannot be mapped back to the original source.
 *
 * This formalizes the existing ad-hoc suppression in the language service
 * plugin's `mapDiagnostic` function.
 */

import type * as ts from "typescript";
import type { DiagnosticSuppressionRule } from "./diagnostic-suppression.js";

/**
 * Callback that maps a transformed-code position back to the original source.
 * Returns `null` if the position is in macro-generated code with no original
 * source correspondence.
 */
export type PositionMapFn = (fileName: string, transformedPos: number) => number | null;

/**
 * Create a MacroGenerated diagnostic suppression rule.
 *
 * This rule suppresses any diagnostic whose source position cannot be mapped
 * back to the original source via the position mapper. Such positions exist
 * only in code generated by macro expansion, where TypeScript's diagnostics
 * are artifacts of the rewrite rather than real user errors.
 *
 * The `mapToOriginal` callback is provided by the transformer or language
 * service plugin at initialization time.
 *
 * @param mapToOriginal - Callback that maps (fileName, transformedPos) → originalPos | null
 */
// Error codes that are expected from macro-generated code and safe to suppress
// when the diagnostic position has no original-source equivalent.
const MACRO_GENERATED_SUPPRESS_CODES = [
  2451, // Cannot redeclare block-scoped variable (namespace + interface merging)
  2304, // Cannot find name (macro-internal references not in scope)
  2339, // Property does not exist (companion object property access)
  6133, // declared but never read (generated variables)
  6196, // declared but never used
];

export function createMacroGeneratedRule(mapToOriginal: PositionMapFn): DiagnosticSuppressionRule {
  return {
    name: "MacroGenerated",
    errorCodes: MACRO_GENERATED_SUPPRESS_CODES,

    shouldSuppress(diagnostic: ts.Diagnostic): boolean {
      if (diagnostic.start === undefined || !diagnostic.file) {
        return false;
      }

      const originalPos = mapToOriginal(diagnostic.file.fileName, diagnostic.start);
      return originalPos === null;
    },
  };
}
