/**
 * Built-in SFINAE Rules
 *
 * Rule 4 (MacroGenerated): Suppresses diagnostics in macro-generated code
 * whose source positions cannot be mapped back to the original source.
 *
 * This formalizes the existing ad-hoc suppression in the language service
 * plugin's `mapDiagnostic` function.
 */

import type * as ts from "typescript";
import type { SfinaeRule } from "./sfinae.js";

/**
 * Callback that maps a transformed-code position back to the original source.
 * Returns `null` if the position is in macro-generated code with no original
 * source correspondence.
 */
export type PositionMapFn = (fileName: string, transformedPos: number) => number | null;

/**
 * Create a MacroGenerated SFINAE rule.
 *
 * This rule suppresses any diagnostic whose source position cannot be mapped
 * back to the original source via the position mapper. Such positions exist
 * only in code generated by macro expansion, where TypeScript's diagnostics
 * are artifacts of the rewrite rather than real user errors.
 *
 * The `mapToOriginal` callback is provided by the transformer or language
 * service plugin at initialization time.
 *
 * @param mapToOriginal - Callback that maps (fileName, transformedPos) → originalPos | null
 */
export function createMacroGeneratedRule(mapToOriginal: PositionMapFn): SfinaeRule {
  return {
    name: "MacroGenerated",
    errorCodes: [], // wildcard — applies to any error code

    shouldSuppress(diagnostic: ts.Diagnostic): boolean {
      if (diagnostic.start === undefined || !diagnostic.file) {
        return false;
      }

      const originalPos = mapToOriginal(diagnostic.file.fileName, diagnostic.start);
      return originalPos === null;
    },
  };
}
