/**
 * Operator Macros
 *
 * Provides named macros for each custom operator:
 * - __pipe__: pipeline operator |> (preprocessor-generated)
 * - __cons__: cons/prepend operator :: (preprocessor-generated)
 * - __apply__: reverse-apply operator <| (preprocessor-generated)
 * - pipe/compose: functional composition macros
 * - getOperatorString: utility to convert TS operator tokens to strings
 *
 * Operator overloading for standard operators (+, -, *, /, etc.) is handled
 * entirely via @op JSDoc tags on typeclass methods. The transformer detects
 * these and rewrites operators globally — no wrapper function needed.
 */

import * as ts from "typescript";
import { defineExpressionMacro, globalRegistry } from "@typesugar/core";
import { MacroContext } from "@typesugar/core";
import { getSyntaxForOperator, findInstance } from "./typeclass.js";

// ============================================================================
// Shared helper — typeclass-based operator resolution
// ============================================================================

function tryTypeclassResolution(
  ctx: MacroContext,
  operator: string,
  left: ts.Expression,
  right: ts.Expression
): ts.Expression | null {
  let baseTypeName = "";
  try {
    const leftType = ctx.getTypeOf(left);
    if (leftType) {
      const typeName = ctx.typeChecker.typeToString(leftType);
      baseTypeName = typeName.split("<")[0].trim();
    }
  } catch {
    return null;
  }

  if (!baseTypeName) return null;

  const syntaxEntries = getSyntaxForOperator(operator);
  if (!syntaxEntries || syntaxEntries.length === 0) return null;

  for (const entry of syntaxEntries) {
    const instance = findInstance(entry.typeclass, baseTypeName, ctx.sourceFile.fileName);
    if (instance) {
      return ctx.factory.createCallExpression(
        ctx.factory.createPropertyAccessExpression(
          ctx.factory.createIdentifier(instance.instanceName),
          entry.method
        ),
        undefined,
        [left, right]
      );
    }
  }

  return null;
}

// ============================================================================
// __pipe__() — Pipeline operator |>
// ============================================================================

/**
 * Emitted by the preprocessor for the pipeline operator.
 *
 * `a |> f` → `__pipe__(a, f)` → `f(a)` (or typeclass dispatch)
 */
export const pipeOpMacro = defineExpressionMacro({
  name: "__pipe__",
  description: "Pipeline operator |> (generated by preprocessor)",

  expand(
    ctx: MacroContext,
    callExpr: ts.CallExpression,
    args: readonly ts.Expression[]
  ): ts.Expression {
    if (args.length !== 2) {
      ctx.reportError(callExpr, "__pipe__ expects exactly 2 arguments: (left, right)");
      return callExpr;
    }

    const [left, right] = args;

    const resolved = tryTypeclassResolution(ctx, "|>", left, right);
    if (resolved) return resolved;

    return ctx.factory.createCallExpression(right, undefined, [left]);
  },
});

// ============================================================================
// __cons__() — Cons/prepend operator ::
// ============================================================================

/**
 * Emitted by the preprocessor for the cons operator.
 *
 * `head :: tail` → `__cons__(head, tail)` → `[head, ...tail]` (or typeclass dispatch)
 */
export const consOpMacro = defineExpressionMacro({
  name: "__cons__",
  description: "Cons operator :: (generated by preprocessor)",

  expand(
    ctx: MacroContext,
    callExpr: ts.CallExpression,
    args: readonly ts.Expression[]
  ): ts.Expression {
    if (args.length !== 2) {
      ctx.reportError(callExpr, "__cons__ expects exactly 2 arguments: (head, tail)");
      return callExpr;
    }

    const [head, tail] = args;

    const resolved = tryTypeclassResolution(ctx, "::", head, tail);
    if (resolved) return resolved;

    return ctx.factory.createArrayLiteralExpression([head, ctx.factory.createSpreadElement(tail)]);
  },
});

// ============================================================================
// __apply__() — Reverse-apply operator <|
// ============================================================================

/**
 * Emitted by the preprocessor for the reverse-apply operator.
 *
 * `f <| x` → `__apply__(f, x)` → `f(x)` (or typeclass dispatch)
 */
export const applyOpMacro = defineExpressionMacro({
  name: "__apply__",
  description: "Reverse-apply operator <| (generated by preprocessor)",

  expand(
    ctx: MacroContext,
    callExpr: ts.CallExpression,
    args: readonly ts.Expression[]
  ): ts.Expression {
    if (args.length !== 2) {
      ctx.reportError(callExpr, "__apply__ expects exactly 2 arguments: (fn, arg)");
      return callExpr;
    }

    const [fn, arg] = args;

    const resolved = tryTypeclassResolution(ctx, "<|", fn, arg);
    if (resolved) return resolved;

    return ctx.factory.createCallExpression(fn, undefined, [arg]);
  },
});

// ============================================================================
// pipe() and compose() - Functional composition macros
// ============================================================================

export const pipeMacro = defineExpressionMacro({
  name: "pipe",
  module: "typesugar",
  description: "Pipe a value through a series of functions",

  expand(
    ctx: MacroContext,
    callExpr: ts.CallExpression,
    args: readonly ts.Expression[]
  ): ts.Expression {
    if (args.length < 2) {
      ctx.reportError(callExpr, "pipe() requires at least an initial value and one function");
      return callExpr;
    }

    const factory = ctx.factory;

    // pipe(x, f, g, h) => h(g(f(x)))
    let result = args[0];

    for (let i = 1; i < args.length; i++) {
      result = factory.createCallExpression(args[i], undefined, [result]);
    }

    return result;
  },
});

export const composeMacro = defineExpressionMacro({
  name: "compose",
  module: "typesugar",
  description: "Compose functions right-to-left",

  expand(
    ctx: MacroContext,
    callExpr: ts.CallExpression,
    args: readonly ts.Expression[]
  ): ts.Expression {
    if (args.length < 1) {
      ctx.reportError(callExpr, "compose() requires at least one function");
      return callExpr;
    }

    const factory = ctx.factory;

    const paramName = ctx.generateUniqueName("x");

    let body: ts.Expression = paramName;
    for (let i = args.length - 1; i >= 0; i--) {
      body = factory.createCallExpression(args[i], undefined, [body]);
    }

    return factory.createArrowFunction(
      undefined,
      undefined,
      [factory.createParameterDeclaration(undefined, undefined, paramName)],
      undefined,
      factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
      body
    );
  },
});

// ============================================================================
// Utility
// ============================================================================

/**
 * Convert a binary operator token to its string representation.
 */
export function getOperatorString(kind: ts.SyntaxKind): string | undefined {
  switch (kind) {
    case ts.SyntaxKind.PlusToken:
      return "+";
    case ts.SyntaxKind.MinusToken:
      return "-";
    case ts.SyntaxKind.AsteriskToken:
      return "*";
    case ts.SyntaxKind.SlashToken:
      return "/";
    case ts.SyntaxKind.PercentToken:
      return "%";
    case ts.SyntaxKind.AsteriskAsteriskToken:
      return "**";
    case ts.SyntaxKind.LessThanToken:
      return "<";
    case ts.SyntaxKind.LessThanEqualsToken:
      return "<=";
    case ts.SyntaxKind.GreaterThanToken:
      return ">";
    case ts.SyntaxKind.GreaterThanEqualsToken:
      return ">=";
    case ts.SyntaxKind.EqualsEqualsToken:
      return "==";
    case ts.SyntaxKind.EqualsEqualsEqualsToken:
      return "===";
    case ts.SyntaxKind.ExclamationEqualsToken:
      return "!=";
    case ts.SyntaxKind.ExclamationEqualsEqualsToken:
      return "!==";
    case ts.SyntaxKind.AmpersandToken:
      return "&";
    case ts.SyntaxKind.BarToken:
      return "|";
    case ts.SyntaxKind.CaretToken:
      return "^";
    case ts.SyntaxKind.LessThanLessThanToken:
      return "<<";
    case ts.SyntaxKind.GreaterThanGreaterThanToken:
      return ">>";
    default:
      return undefined;
  }
}

// Register macros
globalRegistry.register(pipeOpMacro);
globalRegistry.register(consOpMacro);
globalRegistry.register(applyOpMacro);
globalRegistry.register(pipeMacro);
globalRegistry.register(composeMacro);
