/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of transforming a source file */
export interface TransformResult {
  /** The transformed code */
  code: string
  /** Source map (JSON string) */
  map?: string
  /** Whether the code was changed */
  changed: boolean
  /** Any diagnostics/errors */
  diagnostics: Array<Diagnostic>
  /**
   * If true, at least one macro requested fallback to the TypeScript transformer.
   * The pipeline should discard this result and re-transform using the TS backend.
   */
  needsFallback: boolean
}
/** A diagnostic message from the transformer */
export interface Diagnostic {
  severity: string
  message: string
  line?: number
  column?: number
}
/** Transform options */
export interface TransformOptions {
  /** Enable source map generation */
  sourceMap?: boolean
  /** Configuration for conditional compilation (cfg macro) */
  cfgConfig?: Record<string, unknown>
}
/**
 * Transform TypeScript source code using oxc.
 *
 * This is the main entry point for the macro engine.
 * Processes syntax-only macros (cfg, staticAssert) in pure Rust.
 */
export declare function transform(source: string, filename: string, options?: TransformOptions | undefined | null): TransformResult
/**
 * Transform TypeScript source code with JS macro callbacks.
 *
 * This variant allows type-aware macros to be handled by JS callback functions
 * that can access the TypeChecker.
 *
 * The callback receives a JSON-serialized MacroCallInfo and returns a
 * JSON-serialized MacroExpansion.
 *
 * For nested expression macros (like chained `__binop__`), this function
 * iterates until all macros are expanded, since each pass may expose new
 * macro calls that were previously nested inside other macro arguments.
 */
export declare function transformWithMacros(source: string, filename: string, options: TransformOptions | undefined | null, macroCallback: (arg: string) => string): TransformResult
/** Parse TypeScript source and return timing information (for benchmarking) */
export declare function benchmarkParse(source: string, filename: string): BenchmarkResult
/** Benchmark result for parse timing */
export interface BenchmarkResult {
  parseMs: number
  errorCount: number
}
