/**
 * Protocol types for the JS callback API.
 *
 * These types define the JSON protocol for communicating between
 * the Rust traverser and JS macro expansion functions.
 *
 * Note: These are TypeScript-only types (not generated by NAPI-RS).
 */

/** Information about a macro call site, sent to JS callback */
export interface MacroCallInfo {
  /** Name of the macro being invoked (e.g., "typeclass", "impl") */
  macroName: string;
  /** Arguments to the macro as source text strings */
  callSiteArgs: string[];
  /** JSDoc tag value if this is a JSDoc-triggered macro */
  jsDocTag?: string;
  /** Source filename */
  filename: string;
  /** Line number (1-indexed) */
  line: number;
  /** Column number (0-indexed) */
  column: number;
}

/** Kind of AST node the expansion represents */
export type ExpansionKind = "expression" | "statements" | "declaration";

/** A diagnostic from macro expansion */
export interface ExpansionDiagnostic {
  severity: "error" | "warning" | "info";
  message: string;
  line?: number;
  column?: number;
}

/** Result of macro expansion, returned from JS callback */
export interface MacroExpansion {
  /** The expanded code */
  code: string;
  /** What kind of AST node the expansion represents */
  kind: ExpansionKind;
  /** Any diagnostics from the expansion */
  diagnostics: ExpansionDiagnostic[];
  /**
   * If true, this macro requires features not available in the oxc backend
   * (e.g., ts.TransformationContext). The pipeline should fall back to the
   * TypeScript transformer for this file.
   */
  needsFallback?: boolean;
}

/** Type for the macro callback function */
export type MacroCallback = (callInfo: MacroCallInfo) => MacroExpansion;

/**
 * Create a JSON-based macro callback from a typed callback.
 * Wraps the callback to handle JSON serialization/deserialization.
 */
export function createMacroCallback(callback: MacroCallback): (json: string) => string {
  return (json: string): string => {
    const callInfo: MacroCallInfo = JSON.parse(json);
    const expansion = callback(callInfo);
    return JSON.stringify(expansion);
  };
}
