//! @derive
//! Auto-generate implementations

import { derive, Eq, Clone, Debug } from "typesugar";

// Click "JS Output" tab to see the generated code!
// @derive() auto-generates implementations at compile time
// For interfaces: generates standalone functions (pointEq, clonePoint, etc.)
// For classes: generates methods on the class (equals, clone, debug)

// Example with an interface - generates standalone functions
@derive(Eq, Clone, Debug)
interface Point {
  x: number;
  y: number;
}

// Create some points
const p1: Point = { x: 1, y: 2 };
const p2: Point = { x: 1, y: 2 };
const p3: Point = { x: 3, y: 4 };

// These functions are generated by @derive — check JS Output to see them!
// pointEq(a, b): boolean - structural equality
console.log("pointEq(p1, p2):", pointEq(p1, p2));  // true - same values!
console.log("pointEq(p1, p3):", pointEq(p1, p3));  // false

// clonePoint(value): Point - deep copy
const p1Copy = clonePoint(p1);
console.log("clonePoint(p1):", p1Copy);
console.log("Clone equals original:", pointEq(p1Copy, p1));  // true

// debugPoint(value): string - readable representation
console.log("debugPoint(p1):", debugPoint(p1));
// Output: "Point { x: 1, y: 2 }"

// Check the JS Output tab to see the generated functions!
// Each @derive generates predictably named functions:
//   @derive(Eq)    → pointEq(a, b): boolean
//   @derive(Clone) → clonePoint(value): Point
//   @derive(Debug) → debugPoint(value): string
