/**
 * Ambient type declarations for the playground compiler.
 *
 * Only GLOBAL declarations that the transformer emits without explicit imports.
 * Module types (`@typesugar/*`, `effect`, etc.) resolve through real
 * node_modules via workspace symlinks — no stubs needed.
 *
 * Used by api/compile.ts — injected into the compiler host so transformed
 * code can reference typeclass interfaces and primitive instances.
 */

export const AMBIENT_DECLARATIONS = `
// ---------------------------------------------------------------------------
// Globals: primitive instances + typeclass types generated by the transformer
// These are referenced in derived code without explicit imports.
// ---------------------------------------------------------------------------
interface Eq<A> { eq(a: A, b: A): boolean; neq(a: A, b: A): boolean; equals?(a: A, b: A): boolean; notEquals?(a: A, b: A): boolean; }
declare namespace Eq { function registerInstance<T>(name: string, instance: unknown): void; }
interface Ord<A> extends Eq<A> { compare(a: A, b: A): number; lt(a: A, b: A): boolean; gt(a: A, b: A): boolean; lte(a: A, b: A): boolean; gte(a: A, b: A): boolean; }
declare namespace Ord { function registerInstance<T>(name: string, instance: unknown): void; }
interface Clone<A> { clone(a: A): A; }
declare namespace Clone { function registerInstance<T>(name: string, instance: unknown): void; }
interface Debug<A> { debug(a: A): string; }
declare namespace Debug { function registerInstance<T>(name: string, instance: unknown): void; }
interface Hash<A> { hash(a: A): number; }
declare namespace Hash { function registerInstance<T>(name: string, instance: unknown): void; }
interface Show<A> { show(a: A): string; }
declare namespace Show { function registerInstance<T>(name: string, instance: unknown): void; }

declare const eqNumber: Eq<number>;
declare const eqString: Eq<string>;
declare const eqBoolean: Eq<boolean>;
declare const ordNumber: Ord<number>;
declare const ordString: Ord<string>;

// ---------------------------------------------------------------------------
// Runtime helpers emitted by compile-time macros
// ---------------------------------------------------------------------------
declare function __typesugar_createStateMachineInstance(def: any): any;
declare const __typesugar_parser: { grammar(text: string): any };
`;
