/**
 * Ambient type declarations for @typesugar/* packages.
 *
 * These provide the TypeScript type checker with enough information to
 * resolve imports in playground examples, enabling:
 *   1. Extension method rewriting (receiver type must be non-any)
 *   2. @opaque method rewriting (needs to know Option<A> etc.)
 *   3. Type-driven macro optimizations (match exhaustiveness, etc.)
 *
 * Used by api/compile.ts — injected into the compiler host so playground
 * code can import from @typesugar/* without actual node_modules.
 */

export const AMBIENT_DECLARATIONS = `
// ---------------------------------------------------------------------------
// typesugar (umbrella re-exports from @typesugar/core + @typesugar/macros)
// ---------------------------------------------------------------------------
declare module "typesugar" {
  export function comptime<T>(fn: () => T): T;
  export function staticAssert(condition: boolean, message?: string): void;

  export function pipe<A>(a: A): A;
  export function pipe<A, B>(a: A, ab: (a: A) => B): B;
  export function pipe<A, B, C>(a: A, ab: (a: A) => B, bc: (b: B) => C): C;
  export function pipe<A, B, C, D>(a: A, ab: (a: A) => B, bc: (b: B) => C, cd: (c: C) => D): D;
  export function pipe(value: unknown, ...fns: Array<(x: unknown) => unknown>): unknown;

  export function compose<A, B, C>(bc: (b: B) => C, ab: (a: A) => B): (a: A) => C;
  export function compose<A, B, C, D>(cd: (c: C) => D, bc: (b: B) => C, ab: (a: A) => B): (a: A) => D;
  export function compose<A, B, C, D, E>(de: (d: D) => E, cd: (c: C) => D, bc: (b: B) => C, ab: (a: A) => B): (a: A) => E;
  export function flow<A, B, C>(ab: (a: A) => B, bc: (b: B) => C): (a: A) => C;
  export function flow<A, B, C, D>(ab: (a: A) => B, bc: (b: B) => C, cd: (c: C) => D): (a: A) => D;
  export function flow(...fns: Array<(x: unknown) => unknown>): (x: unknown) => unknown;

  export function derive(...traits: unknown[]): ClassDecorator;
  export function summon<TC>(...args: unknown[]): unknown;
  export function implicit<TC>(...args: unknown[]): unknown;

  export function specialize<F extends (...args: any[]) => any>(fn: F): F;
  export function specialize<F extends (...args: any[]) => any>(fn: F, dictionary: unknown): F;

  export function reflect<T>(): unknown;
  export function typeInfo<T>(): { name: string; kind: string; fields?: Array<{ name: string; type: string }> };
  export function fieldNames<T>(): string[];

  export function cfg<T>(condition: string, thenValue: T, elseValue?: T): T;
  export function tailrec<A, B>(fn: (recurse: (a: A) => B, a: A) => B): (a: A) => B;
  export function tailrec(target: Function, context?: ClassMethodDecoratorContext): Function;

  export interface Eq<A> { eq(a: A, b: A): boolean; neq(a: A, b: A): boolean; equals?(a: A, b: A): boolean; notEquals?(a: A, b: A): boolean; }
  export namespace Eq { function registerInstance<T>(name: string, instance: unknown): void; }
  export interface Ord<A> extends Eq<A> { compare(a: A, b: A): number; lt(a: A, b: A): boolean; gt(a: A, b: A): boolean; lte(a: A, b: A): boolean; gte(a: A, b: A): boolean; }
  export namespace Ord { function registerInstance<T>(name: string, instance: unknown): void; }
  export interface Clone<A> { clone(a: A): A; }
  export namespace Clone { function registerInstance<T>(name: string, instance: unknown): void; }
  export interface Debug<A> { debug(a: A): string; }
  export namespace Debug { function registerInstance<T>(name: string, instance: unknown): void; }
  export interface Hash<A> { hash(a: A): number; }
  export namespace Hash { function registerInstance<T>(name: string, instance: unknown): void; }
  export interface Show<A> { show(a: A): string; }
  export namespace Show { function registerInstance<T>(name: string, instance: unknown): void; }
}

// ---------------------------------------------------------------------------
// Globals: primitive instances + typeclass types generated by the transformer
// These are referenced in derived code without explicit imports.
// ---------------------------------------------------------------------------
interface Eq<A> { eq(a: A, b: A): boolean; neq(a: A, b: A): boolean; equals?(a: A, b: A): boolean; notEquals?(a: A, b: A): boolean; }
declare namespace Eq { function registerInstance<T>(name: string, instance: unknown): void; }
interface Ord<A> extends Eq<A> { compare(a: A, b: A): number; lt(a: A, b: A): boolean; gt(a: A, b: A): boolean; lte(a: A, b: A): boolean; gte(a: A, b: A): boolean; }
declare namespace Ord { function registerInstance<T>(name: string, instance: unknown): void; }
interface Clone<A> { clone(a: A): A; }
declare namespace Clone { function registerInstance<T>(name: string, instance: unknown): void; }
interface Debug<A> { debug(a: A): string; }
declare namespace Debug { function registerInstance<T>(name: string, instance: unknown): void; }
interface Hash<A> { hash(a: A): number; }
declare namespace Hash { function registerInstance<T>(name: string, instance: unknown): void; }
interface Show<A> { show(a: A): string; }
declare namespace Show { function registerInstance<T>(name: string, instance: unknown): void; }

declare const eqNumber: Eq<number>;
declare const eqString: Eq<string>;
declare const eqBoolean: Eq<boolean>;
declare const ordNumber: Ord<number>;
declare const ordString: Ord<string>;

// ---------------------------------------------------------------------------
// @typesugar/fp/data/option — subpath import used by transformer
// ---------------------------------------------------------------------------
declare module "@typesugar/fp/data/option" {
  export function map<A, B>(self: A | null, f: (a: A) => B): B | null;
  export function flatMap<A, B>(self: A | null, f: (a: A) => B | null): B | null;
  export function fold<A, B>(self: A | null, onNone: () => B, onSome: (a: A) => B): B;
  export function getOrElse<A>(self: A | null, defaultValue: () => A): A;
  export function getOrElseStrict<A>(self: A | null, defaultValue: A): A;
  export function getOrThrow<A>(self: A | null, message?: string): A;
  export function orElse<A>(self: A | null, fallback: () => A | null): A | null;
  export function filter<A>(self: A | null, predicate: (a: A) => boolean): A | null;
  export function exists<A>(self: A | null, predicate: (a: A) => boolean): boolean;
  export function forall<A>(self: A | null, predicate: (a: A) => boolean): boolean;
  export function contains<A>(self: A | null, value: A): boolean;
  export function tap<A>(self: A | null, f: (a: A) => void): A | null;
  export function toArray<A>(self: A | null): A[];
  export function toNullable<A>(self: A | null): A | null;
  export function toUndefined<A>(self: A | null): A | undefined;
  export function zip<A, B>(self: A | null, optB: B | null): [A, B] | null;
}

// ---------------------------------------------------------------------------
// @typesugar/fp — Option (null-based @opaque), Either, List, Validated
// ---------------------------------------------------------------------------
declare module "@typesugar/fp" {
  export interface Option<A> {
    map<B>(f: (a: A) => B): Option<B>;
    flatMap<B>(f: (a: A) => Option<B>): Option<B>;
    fold<B>(onNone: () => B, onSome: (a: A) => B): B;
    getOrElse(defaultValue: () => A): A;
    getOrElseStrict(defaultValue: A): A;
    getOrThrow(message?: string): A;
    orElse(fallback: () => Option<A>): Option<A>;
    filter(predicate: (a: A) => boolean): Option<A>;
    exists(predicate: (a: A) => boolean): boolean;
    forall(predicate: (a: A) => boolean): boolean;
    contains(value: A): boolean;
    tap(f: (a: A) => void): Option<A>;
    toArray(): A[];
    toNullable(): A | null;
    toUndefined(): A | undefined;
    zip<B>(optB: Option<B>): Option<[A, B]>;
    toString(): string;
  }

  export function Some<A>(value: A): Option<A>;
  export const None: Option<never>;
  export function isSome<A>(opt: Option<A>): boolean;
  export function isNone<A>(opt: Option<A>): boolean;

  export interface Either<E, A> {
    readonly _tag: "Left" | "Right";
    map<B>(f: (a: A) => B): Either<E, B>;
    flatMap<B>(f: (a: A) => Either<E, B>): Either<E, B>;
    fold<B>(onLeft: (e: E) => B, onRight: (a: A) => B): B;
    getOrElse(defaultValue: () => A): A;
    isLeft(): boolean;
    isRight(): boolean;
    toString(): string;
  }

  export function Left<E, A = never>(left: E): Either<E, A>;
  export function Right<E = never, A = unknown>(right: A): Either<E, A>;
  export function isLeft<E, A>(either: Either<E, A>): boolean;
  export function isRight<E, A>(either: Either<E, A>): boolean;

  export type List<A> = { readonly _tag: "Cons"; readonly head: A; readonly tail: List<A> } | { readonly _tag: "Nil" };
  export function Cons<A>(head: A, tail: List<A>): List<A>;
  export const Nil: List<never>;
  export function listOf<A>(...items: A[]): List<A>;
  export function isCons<A>(list: List<A>): boolean;
  export function isNil<A>(list: List<A>): boolean;

  export type NonEmptyList<A> = { readonly head: A; readonly tail: readonly A[] };
  export function nonEmptyListOf<A>(head: A, ...rest: A[]): NonEmptyList<A>;

  export type ValidatedNel<E, A> = { readonly _tag: "Valid"; readonly value: A } | { readonly _tag: "Invalid"; readonly error: NonEmptyList<E> };
  export function Validated<E, A>(value: A): ValidatedNel<E, A>;
  export function validNel<E, A>(value: A): ValidatedNel<E, A>;
  export function invalidNel<E, A>(error: E): ValidatedNel<E, A>;
  export namespace Validated {
    function mapN<E, A, B, R>(va: ValidatedNel<E, A>, vb: ValidatedNel<E, B>, f: (a: A, b: B) => R): ValidatedNel<E, R>;
    function mapN<E, A, B, C, R>(va: ValidatedNel<E, A>, vb: ValidatedNel<E, B>, vc: ValidatedNel<E, C>, f: (a: A, b: B, c: C) => R): ValidatedNel<E, R>;
    function mapN<E, A, B, C, D, R>(va: ValidatedNel<E, A>, vb: ValidatedNel<E, B>, vc: ValidatedNel<E, C>, vd: ValidatedNel<E, D>, f: (a: A, b: B, c: C, d: D) => R): ValidatedNel<E, R>;
  }

  export function pipe<A>(a: A): A;
  export function pipe<A, B>(a: A, ab: (a: A) => B): B;
  export function pipe<A, B, C>(a: A, ab: (a: A) => B, bc: (b: B) => C): C;
  export function pipe(value: unknown, ...fns: Array<(x: unknown) => unknown>): unknown;
}

// ---------------------------------------------------------------------------
// @typesugar/std — match, extensions, ranges, Eq/Hash
// ---------------------------------------------------------------------------
declare module "@typesugar/std" {
  export function match<T>(value: T): MatchBuilder<T>;

  interface MatchBuilder<T> {
    case(pattern: any): CaseArm<T>;
    else<R>(defaultValue: R): R;
  }
  interface CaseArm<T> {
    or(pattern: any): CaseArm<T>;
    if(guard: (value: T) => boolean): CaseArm<T>;
    then<R>(result: R): ThenArm<T, R>;
  }
  interface ThenArm<T, R> {
    case(pattern: any): CaseArm<T>;
    else<R2>(defaultValue: R2): R | R2;
  }

  export function clamp(n: number, min: number, max: number): number;
  export function isEven(n: number): boolean;
  export function isPrime(n: number): boolean;
  export function toHex(n: number): string;
  export function toRoman(n: number): string;
  export function capitalize(s: string): string;
  export function kebabCase(s: string): string;
  export function reverse(s: string): string;
  export function isPalindrome(s: string): boolean;

  export interface Range {
    readonly start: number;
    readonly end: number;
    readonly step: number;
    readonly inclusive: boolean;
  }
  export function range(start: number, end: number, step?: number): Range;
  export function rangeInclusive(start: number, end: number, step?: number): Range;
  export function rangeToArray(r: Range): number[];
  export function rangeMap<A>(r: Range, fn: (n: number, index: number) => A): A[];
  export function rangeFilter(r: Range, pred: (n: number) => boolean): number[];
  export function rangeReduce<A>(r: Range, init: A, fn: (acc: A, n: number) => A): A;
  export function rangeForEach(r: Range, fn: (n: number, index: number) => void): void;
  export function rangeContains(r: Range, value: number): boolean;
  export function rangeSize(r: Range): number;

  export interface Eq<A> { eqv(a: A, b: A): boolean; eq(a: A, b: A): boolean; neq(a: A, b: A): boolean; equals?(a: A, b: A): boolean; }
  export interface Hash<A> { hash(a: A): number; }
  /** @op + */ /** @op - */ /** @op * */ /** @op / */ /** @op ** */
  export interface Numeric<A> {
    add(a: A, b: A): A;
    sub(a: A, b: A): A;
    mul(a: A, b: A): A;
    div(a: A, b: A): A;
    pow(a: A, b: A): A;
    negate(a: A): A;
    abs(a: A): A;
    signum(a: A): A;
    fromNumber(n: number): A;
    toNumber(a: A): number;
    zero(): A;
    one(): A;
  }
  export const eqNumber: Eq<number>;
  export const eqString: Eq<string>;
  export const eqBoolean: Eq<boolean>;
  export const hashNumber: Hash<number>;
  export function makeEq<A>(fn: (a: A, b: A) => boolean): Eq<A>;
  export function makeHash<A>(fn: (a: A) => number): Hash<A>;
}

// ---------------------------------------------------------------------------
// @typesugar/testing
// ---------------------------------------------------------------------------
declare module "@typesugar/testing" {
  export function assert(condition: boolean, message?: string): void;
  export function typeAssert<_T extends true>(): void;
  export function staticAssert(condition: boolean, message?: string): void;
  export type Equal<A, B> = A extends B ? (B extends A ? true : false) : false;
  export type Extends<A, B> = A extends B ? true : false;
  export type Not<T extends boolean> = T extends true ? false : true;
}

// ---------------------------------------------------------------------------
// @typesugar/collections
// ---------------------------------------------------------------------------
declare module "@typesugar/collections" {
  export class HashSet<K> {
    constructor(eq: { eqv(a: K, b: K): boolean }, hash: { hash(a: K): number });
    get size(): number;
    has(k: K): boolean;
    add(k: K): this;
    delete(k: K): boolean;
    clear(): void;
    values(): IterableIterator<K>;
    [Symbol.iterator](): IterableIterator<K>;
  }
  export class HashMap<K, V> {
    constructor(eq: { eqv(a: K, b: K): boolean }, hash: { hash(a: K): number });
    get size(): number;
    get(k: K): V | undefined;
    getOrElse(k: K, defaultValue: V): V;
    has(k: K): boolean;
    set(k: K, v: V): this;
    delete(k: K): boolean;
    clear(): void;
    keys(): IterableIterator<K>;
    values(): IterableIterator<V>;
    entries(): IterableIterator<[K, V]>;
  }
}

// ---------------------------------------------------------------------------
// @typesugar/contracts
// ---------------------------------------------------------------------------
declare module "@typesugar/contracts" {
  export function requires(condition: boolean, message?: string): void;
  export function ensures(condition: boolean, message?: string): void;
  export function old<T>(expr: T): T;
  export class PreconditionError extends Error {}
  export class PostconditionError extends Error {}
  export class InvariantError extends Error {}
}

// ---------------------------------------------------------------------------
// @typesugar/validate
// ---------------------------------------------------------------------------
declare module "@typesugar/validate" {
  export function is<T>(): (value: unknown) => value is T;
  export function assert<T>(): (value: unknown) => T;
}

// ---------------------------------------------------------------------------
// @typesugar/graph
// ---------------------------------------------------------------------------
declare module "@typesugar/graph" {
  export interface Transition { from: string; event: string; to: string; }
  export interface StateMachineDefinition {
    states: ReadonlyArray<string>;
    transitions: ReadonlyArray<Transition>;
    initial: string;
    terminal?: ReadonlyArray<string>;
    create<S extends string = string, E extends string = string>(): StateMachineInstance<S, E>;
  }
  export interface StateMachineInstance<S extends string, E extends string> {
    readonly current: S;
    transition(event: E): StateMachineInstance<S, E>;
    canTransition(event: E): boolean;
    availableEvents(): E[];
  }
  export interface VerificationResult {
    valid: boolean;
    unreachableStates: ReadonlyArray<string>;
    deadEndStates: ReadonlyArray<string>;
    nondeterministic: ReadonlyArray<{ state: string; event: string; targets: string[] }>;
    cycles: ReadonlyArray<ReadonlyArray<string>>;
  }
  export interface Graph {
    nodes: ReadonlyArray<{ id: string }>;
    edges: ReadonlyArray<{ from: string; to: string; weight?: number }>;
    directed: boolean;
  }
  export function digraph(strings: TemplateStringsArray, ...values: unknown[]): Graph;
  export function stateMachine(strings: TemplateStringsArray, ...values: unknown[]): StateMachineDefinition;
  export function verify(sm: StateMachineDefinition): VerificationResult;
  export function createInstance<S extends string, E extends string>(sm: StateMachineDefinition): StateMachineInstance<S, E>;
  export function deadEndStates(sm: StateMachineDefinition): string[];
  export function shortestPath(graph: Graph, from: string, to: string): string[] | null;
  export function topoSort(graph: Graph): string[];
  export function hasCycles(graph: Graph): boolean;
  export function dijkstra(graph: Graph, start: string): Map<string, number>;
}

// ---------------------------------------------------------------------------
// @typesugar/codec
// ---------------------------------------------------------------------------
declare module "@typesugar/codec" {
  export interface FieldMeta {
    name: string; type: string; since?: number; removed?: number;
    renamed?: { version: number; oldName: string }; defaultValue?: unknown; optional?: boolean;
  }
  export interface Schema { name: string; version: number; format: "json" | "binary"; fields: FieldMeta[]; }
  export interface Codec<T> { encode(data: T): unknown; decode(data: unknown): T; }
  export class SchemaBuilder<T> {
    constructor(name: string, version: number, format?: "json" | "binary");
    field(name: string, type: string, options?: Partial<FieldMeta>): this;
    build(): Schema;
    buildCodec(): Codec<T>;
  }
  export function schema<T>(name: string, version: number, format?: "json" | "binary"): SchemaBuilder<T>;
}

// ---------------------------------------------------------------------------
// @typesugar/units
// ---------------------------------------------------------------------------
declare module "@typesugar/units" {
  export interface Unit<D> {
    value: number;
    div(other: Unit<unknown>): Unit<unknown>;
    add(other: Unit<D>): Unit<D>;
    mul(other: Unit<unknown>): Unit<unknown>;
    toString(): string;
  }
  export function units(strings: TemplateStringsArray): Unit<unknown>;
  export function meters(value: number): Unit<unknown>;
  export function seconds(value: number): Unit<unknown>;
  export function kilograms(value: number): Unit<unknown>;
  export function newtons(value: number): Unit<unknown>;
  export function kilometers(value: number): Unit<unknown>;
  export function hours(value: number): Unit<unknown>;
}

// ---------------------------------------------------------------------------
// @typesugar/effect
// ---------------------------------------------------------------------------
declare module "@typesugar/effect" {
  export interface Effect<R, E, A> {
    readonly _R: (_: R) => void;
    readonly _E: () => E;
    readonly _A: () => A;
  }
  export function succeed<A>(value: A): Effect<unknown, never, A>;
  export function fail<E>(error: E): Effect<unknown, E, never>;
  export function resolveLayer<R>(): unknown;
  export function layerMake<R>(...layers: unknown[]): unknown;
}

// ---------------------------------------------------------------------------
// @typesugar/math
// ---------------------------------------------------------------------------
declare module "@typesugar/math" {
  import type { Numeric } from "@typesugar/std";
  export interface Rational { readonly num: bigint; readonly den: bigint; }
  export function rational(num: bigint, den: bigint): Rational;
  export function rat(num: number, den: number): Rational;
  export interface Complex { readonly re: number; readonly im: number; }
  export function complex(re: number, im: number): Complex;
  export const numericComplex: Numeric<Complex>;
  export function complexToString(z: Complex): string;
  export function complexMagnitude(z: Complex): number;
  export function complexEquals(a: Complex, b: Complex, epsilon?: number): boolean;
  export interface Matrix<R extends number, C extends number> { readonly rows: R; readonly cols: C; }
  export function matrix<R extends number, C extends number>(rows: R, cols: C, data: number[]): Matrix<R, C>;
  export interface Interval { readonly lo: number; readonly hi: number; }
  export function interval(lo: number, hi: number): Interval;
}

// ---------------------------------------------------------------------------
// @typesugar/symbolic
// ---------------------------------------------------------------------------
declare module "@typesugar/symbolic" {
  import type { Numeric } from "@typesugar/std";
  export interface Expression<T = number> { readonly kind: string; }
  export function var_(name: string): Expression<number>;
  export function const_(value: number): Expression<number>;
  export function add(a: Expression<number>, b: Expression<number>): Expression<number>;
  export function mul(a: Expression<number>, b: Expression<number>): Expression<number>;
  export function pow(base: Expression<number>, exp: Expression<number>): Expression<number>;
  export function sin(arg: Expression<number>): Expression<number>;
  export function cos(arg: Expression<number>): Expression<number>;
  export function diff(expr: Expression<number>, variable: string): Expression<number>;
  export function integrate(expr: Expression<number>, variable: string): Expression<number>;
  export function simplify(expr: Expression<number>): Expression<number>;
  export function evaluate(expr: Expression<number>, vars: Record<string, number>): number;
  export function toText(expr: Expression<number>): string;
  export function toLatex(expr: Expression<number>): string;
  export const numericExpr: Numeric<Expression<number>>;
}

// ---------------------------------------------------------------------------
// @typesugar/parser
// ---------------------------------------------------------------------------
declare module "@typesugar/parser" {
  export type ParseResult<T> = { success: true; value: T } | { success: false; error: string };
  export function grammar(strings: TemplateStringsArray, ...values: unknown[]): unknown;
  export function literal(s: string): (input: string) => ParseResult<string>;
  export function digit(): (input: string) => ParseResult<string>;
  export function many1<T>(p: (input: string) => ParseResult<T>): (input: string) => ParseResult<T[]>;
  export function map<T, U>(p: (input: string) => ParseResult<T>, fn: (t: T) => U): (input: string) => ParseResult<U>;
  export function seq<T extends unknown[]>(
    ...parsers: { [K in keyof T]: (input: string) => ParseResult<T[K]> }
  ): (input: string) => ParseResult<T>;
  export function alt<T>(...parsers: Array<(input: string) => ParseResult<T>>): (input: string) => ParseResult<T>;
  export function between<L, T, R>(
    left: (input: string) => ParseResult<L>,
    inner: (input: string) => ParseResult<T>,
    right: (input: string) => ParseResult<R>
  ): (input: string) => ParseResult<T>;
  export function lazy<T>(fn: () => (input: string) => ParseResult<T>): (input: string) => ParseResult<T>;
  export function token<T>(p: (input: string) => ParseResult<T>): (input: string) => ParseResult<T>;
}

// ---------------------------------------------------------------------------
// @typesugar/core (direct usage rare in examples, but imported transitively)
// ---------------------------------------------------------------------------
declare module "@typesugar/core" {
  export interface MacroContext {
    readonly program: any;
    readonly sourceFile: any;
    readonly factory: any;
    readonly checker: any;
  }
  export function defineExpressionMacro(opts: any): any;
  export function defineAttributeMacro(opts: any): any;
}

// ---------------------------------------------------------------------------
// @typesugar/type-system
// ---------------------------------------------------------------------------
declare module "@typesugar/type-system" {
  export type _ = { readonly _: unique symbol };
  export type Head<T extends any[]> = T extends [infer H, ...any[]] ? H : never;
  export type Tail<T extends any[]> = T extends [any, ...infer R] ? R : never;
}

// ---------------------------------------------------------------------------
// @typesugar/mapper
// ---------------------------------------------------------------------------
declare module "@typesugar/mapper" {
  export function createMapper<S, T>(mapping: Record<string, string | ((s: S) => any)>): (source: S) => T;
}

// ---------------------------------------------------------------------------
// Runtime helpers emitted by compile-time macros
// ---------------------------------------------------------------------------
declare function __typesugar_createStateMachineInstance(def: any): any;
declare const __typesugar_parser: { grammar(text: string): any };
`;
